name: GOTTV Daily Update

on:
  schedule:
    - cron: '0 21 * * *'  # UTC时间21:00 = 北京时间5:00
  workflow_dispatch:  # 添加手动触发选项

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome and Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_PATH=$(which chromium-browser)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests eventlet

      - name: Run IPTV Updater
        env:
          CHROME_PATH: ${{ env.CHROME_PATH }}
        run: python GOTTV.py  # 确保脚本配置了无头模式选项

      - name: Validate Output
        run: |
          if [ ! -s GOTTV.txt ]; then
            echo "::error::生成的GOTTV.txt文件为空或不存在！"
            exit 1
          fi
          echo "文件验证通过，记录数：$(grep -c 'EXTINF' GOTTV.txt)"

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "l19270149853"
          git config --global user.email "362213335lkh@gmail.com"
          
          # 智能检测文件变化
          git add GOTTV.txt
          if git diff-index --quiet HEAD --; then
            echo "没有检测到内容变化，跳过提交"
          else
            git commit -m "自动更新IPTV列表 $(date +'%Y-%m-%d %H:%M')"
            echo "准备推送更改..."
          fi

      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true  # 保留强制推送以防历史冲突
